name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:
#   HELM_EXPERIMENTAL_OCI: 1

jobs:

  build_push_image:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

    - run: mkdir staging && cp target/*.jar staging

    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-demo:latest
    
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1

    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login bcglabacr01.azurecr.io --username bcglabacr01 --password vQign8/X5HO3XhfXFWFW05CtHqpYV+dM

    - name: Package the helm chart
      run: helm package ./helm/albert01-api

    - name: save helm chart to local registry
      run: |
       helm chart save ./albert01-api-0.1.0.tgz bcglabacr01.azurecr.io/charts-albert01-api:latest

    - name: Helm chart Push
      run: helm chart push bcglabacr01.azurecr.io/charts-albert01-api:latest


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_push_image # Will wait for the execution of the previous job 

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Kubernetes set context
  #     uses: Azure/k8s-set-context@v1
  #     with:
  #       kubeconfig: ${{secrets.KUBECONFIG}} # Grab the auth token from GitHub secrets
  #     id: login

  #   - name: Helm tool installer
  #     uses: Azure/setup-helm@v1
  #     with:
  #       # Version of helm
  #       version: 3.3.1

  #   - name: Login to ACR using HELM
  #     run: |
  #       echo $ | helm registry login bcglabacr01.azurecr.io --username bcglabacr01 --password vQign8/X5HO3XhfXFWFW05CtHqpYV+dM

  #   - name: Helm Chart Pull
  #     run: helm chart pull bcglabacr01.azurecr.io/charts-albert01-api:latest

  #   - name: Helm Chart Move
  #     run: helm chart export bcglabacr01.azurecr.io/charts-albert01-api:latest --destination ./install

  #   - name: Helm Chart Install
  #     run: helm upgrade --namespace ns-qa --install --set image.tag=latest albert01-api ./install/albert01-api # release name chart name
  #   #Declarative Deployment-02
  #   - name: Kubernetes Deployment
  #     run: kubectl apply -f deployment.yaml
  #   - name: Service Deployment
  #     run: kubectl apply -f service.yaml